#!/usr/bin/env python
#------------
# Usage: npm.htpasswd <username>

import sys
import crypt
import getpass
import os
import argparse

from datetime import datetime

parser = argparse.ArgumentParser()
parser.add_argument("username", help="Nombre de usuario")
parser.add_argument("-p", "--path", help="Ruta al fichero de claves")
args = parser.parse_args()

# Usar un salt para sha-512 con 16 bytes de longitud
salt   = "$6$%s$" % os.urandom(16).encode('base_64').strip()
passwd = getpass.getpass("Password: ")
hashed = crypt.crypt(passwd, salt)
prefix = "%s:" % args.username
# Isoformat devuelve microsegundos, y el formato nativo de sinopia
# se queda en milisegundos
stamp  = "autocreated %sZ" % datetime.utcnow().isoformat()[:-3]
result = "%s:%s:%s\n" % (args.username, hashed, stamp)

lines = tuple()
if args.path:
    try:
        with open(args.path, "r") as infile:
            lines = list(l for l in infile.readlines()
                          if not l.startswith(prefix))
    except IOError:
        print("Coulde not read file %s" & args.path)
        sys.exit(-1)
    else:
        lines.append(result)
        result = "".join(lines)
    try:
        with open(args.path, "w+") as outfile:
            outfile.write(result)
    except IOError:
        print("Could not write to file %s" % args.path)
        sys.exit(-2)
else:
    print(result)
