---
# Creacion de blades

# Es J*DIDAMENTE COMPLICADO ejecutar LXCs con un usuario que no sea el
# de inicio de sesion ( ver:
# - https://gist.github.com/julianlam/4e2bd91d8dedee21ca6f
# - Los comentarios con WARN en https://www.stgraber.org/2014/01/17/lxc-1-0-unprivileged-containers/ )
#
# Para evitar estos problemas, tengo que hacver que el usuario que inicia
# la conexion en ansible sea directamente el usuario destinado a ejecutar
# los contenedores.

- name: Create LXC blades
  when: ansible_user_id == lxc_user
  tags: blades
  lxc_container:
    name: "{{ item.name }}"
    template: download
    template_options: "{{ lxc_template }}"
    state: started
    backing_store: dir
    config: "/home/{{ lxc_user }}/.config/lxc/default.conf"
    directory: "{{ lxc_path }}/root/{{ item.name }}"
    lxc_path:  "{{ lxc_path }}/lxc/{{ item.name }}"
  with_items: "{{ blades }}"

