---

# Se debe ejecutar con una variable "bootstrap"
# (ansible playbook -e bootstrap=True|False ...)
# que indica si el cluster es nuevo, o ya existe.

# Instalacion de paquetes requeridos
- include: install.yml
  tags: install

# Configuracion de networking
- include: network.yml
  tags: network

# Descarga de imagenes CoreOS
- include: download.yml
  tags: download

# Configuracion de almacenamiento ZFS
- include: storage-zfs.yml
  tags: storage
  when: zfs_path is defined and zfs_path

# Configuracion de almacenamiento LVM
- include: storage-lvm.yml
  tags: storage
  when: lvm_vg is defined and lvm_vg

# Despliegue de maquinas virtuales
- include: deploy.yml
  tags: deploy
