---

# Se debe ejecutar con una variable "bootstrap"
# (ansible playbook -e bootstrap=True|False ...)
# que indica si el cluster es nuevo, o ya existe.

# Instalacion de paquetes requeridos
- include: install.yml
  tags: install

# Configuracion de networking
- include: network.yml
  tags: network

# Descarga de imagenes CoreOS
- include: download.yml
  tags: download

# Configuracion de almacenamiento ZFS
- include: storage.yml
  tags: storage

# Despliegue de maquinas virtuales
- include: deploy.yml
  tags: deploy
